//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Roberlibrary
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class PDVEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto PDVEntities usando la cadena de conexión encontrada en la sección 'PDVEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public PDVEntities() : base("name=PDVEntities", "PDVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PDVEntities.
        /// </summary>
        public PDVEntities(string connectionString) : base(connectionString, "PDVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PDVEntities.
        /// </summary>
        public PDVEntities(EntityConnection connection) : base(connection, "PDVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto> Producto
        {
            get
            {
                if ((_Producto == null))
                {
                    _Producto = base.CreateObjectSet<Producto>("Producto");
                }
                return _Producto;
            }
        }
        private ObjectSet<Producto> _Producto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Receta> Receta
        {
            get
            {
                if ((_Receta == null))
                {
                    _Receta = base.CreateObjectSet<Receta>("Receta");
                }
                return _Receta;
            }
        }
        private ObjectSet<Receta> _Receta;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Venta> Venta
        {
            get
            {
                if ((_Venta == null))
                {
                    _Venta = base.CreateObjectSet<Venta>("Venta");
                }
                return _Venta;
            }
        }
        private ObjectSet<Venta> _Venta;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Producto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProducto(Producto producto)
        {
            base.AddObject("Producto", producto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Receta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToReceta(Receta receta)
        {
            base.AddObject("Receta", receta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Venta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVenta(Venta venta)
        {
            base.AddObject("Venta", venta);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDVModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Producto CreateProducto(global::System.Int64 id)
        {
            Producto producto = new Producto();
            producto.id = id;
            return producto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodigoBarras
        {
            get
            {
                return _CodigoBarras;
            }
            set
            {
                OnCodigoBarrasChanging(value);
                ReportPropertyChanging("CodigoBarras");
                _CodigoBarras = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodigoBarras");
                OnCodigoBarrasChanged();
            }
        }
        private global::System.String _CodigoBarras;
        partial void OnCodigoBarrasChanging(global::System.String value);
        partial void OnCodigoBarrasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StockMinimo
        {
            get
            {
                return _StockMinimo;
            }
            set
            {
                OnStockMinimoChanging(value);
                ReportPropertyChanging("StockMinimo");
                _StockMinimo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockMinimo");
                OnStockMinimoChanged();
            }
        }
        private Nullable<global::System.Decimal> _StockMinimo;
        partial void OnStockMinimoChanging(Nullable<global::System.Decimal> value);
        partial void OnStockMinimoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StockMaximo
        {
            get
            {
                return _StockMaximo;
            }
            set
            {
                OnStockMaximoChanging(value);
                ReportPropertyChanging("StockMaximo");
                _StockMaximo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockMaximo");
                OnStockMaximoChanged();
            }
        }
        private Nullable<global::System.Decimal> _StockMaximo;
        partial void OnStockMaximoChanging(Nullable<global::System.Decimal> value);
        partial void OnStockMaximoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Existencia
        {
            get
            {
                return _Existencia;
            }
            set
            {
                OnExistenciaChanging(value);
                ReportPropertyChanging("Existencia");
                _Existencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Existencia");
                OnExistenciaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Existencia;
        partial void OnExistenciaChanging(Nullable<global::System.Decimal> value);
        partial void OnExistenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Capacidad
        {
            get
            {
                return _Capacidad;
            }
            set
            {
                OnCapacidadChanging(value);
                ReportPropertyChanging("Capacidad");
                _Capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Capacidad");
                OnCapacidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _Capacidad;
        partial void OnCapacidadChanging(Nullable<global::System.Decimal> value);
        partial void OnCapacidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnidadMedida
        {
            get
            {
                return _UnidadMedida;
            }
            set
            {
                OnUnidadMedidaChanging(value);
                ReportPropertyChanging("UnidadMedida");
                _UnidadMedida = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnidadMedida");
                OnUnidadMedidaChanged();
            }
        }
        private global::System.String _UnidadMedida;
        partial void OnUnidadMedidaChanging(global::System.String value);
        partial void OnUnidadMedidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrecioUnitario
        {
            get
            {
                return _PrecioUnitario;
            }
            set
            {
                OnPrecioUnitarioChanging(value);
                ReportPropertyChanging("PrecioUnitario");
                _PrecioUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioUnitario");
                OnPrecioUnitarioChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrecioUnitario;
        partial void OnPrecioUnitarioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioUnitarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> VistaPublico
        {
            get
            {
                return _VistaPublico;
            }
            set
            {
                OnVistaPublicoChanging(value);
                ReportPropertyChanging("VistaPublico");
                _VistaPublico = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VistaPublico");
                OnVistaPublicoChanged();
            }
        }
        private Nullable<global::System.Boolean> _VistaPublico;
        partial void OnVistaPublicoChanging(Nullable<global::System.Boolean> value);
        partial void OnVistaPublicoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDVModel", Name="Receta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Receta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Receta.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Receta CreateReceta(global::System.Int64 id)
        {
            Receta receta = new Receta();
            receta.id = id;
            return receta;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_rec
        {
            get
            {
                return _id_rec;
            }
            set
            {
                Onid_recChanging(value);
                ReportPropertyChanging("id_rec");
                _id_rec = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_rec");
                Onid_recChanged();
            }
        }
        private Nullable<global::System.Int64> _id_rec;
        partial void Onid_recChanging(Nullable<global::System.Int64> value);
        partial void Onid_recChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                Onid_productoChanging(value);
                ReportPropertyChanging("id_producto");
                _id_producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_producto");
                Onid_productoChanged();
            }
        }
        private Nullable<global::System.Int64> _id_producto;
        partial void Onid_productoChanging(Nullable<global::System.Int64> value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cantidad;
        partial void OnCantidadChanging(Nullable<global::System.Decimal> value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Preparacion
        {
            get
            {
                return _Preparacion;
            }
            set
            {
                OnPreparacionChanging(value);
                ReportPropertyChanging("Preparacion");
                _Preparacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Preparacion");
                OnPreparacionChanged();
            }
        }
        private global::System.String _Preparacion;
        partial void OnPreparacionChanging(global::System.String value);
        partial void OnPreparacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroPersonas
        {
            get
            {
                return _NumeroPersonas;
            }
            set
            {
                OnNumeroPersonasChanging(value);
                ReportPropertyChanging("NumeroPersonas");
                _NumeroPersonas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroPersonas");
                OnNumeroPersonasChanged();
            }
        }
        private global::System.String _NumeroPersonas;
        partial void OnNumeroPersonasChanging(global::System.String value);
        partial void OnNumeroPersonasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Categoria
        {
            get
            {
                return _Categoria;
            }
            set
            {
                OnCategoriaChanging(value);
                ReportPropertyChanging("Categoria");
                _Categoria = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Categoria");
                OnCategoriaChanged();
            }
        }
        private global::System.String _Categoria;
        partial void OnCategoriaChanging(global::System.String value);
        partial void OnCategoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoPreparacion
        {
            get
            {
                return _TiempoPreparacion;
            }
            set
            {
                OnTiempoPreparacionChanging(value);
                ReportPropertyChanging("TiempoPreparacion");
                _TiempoPreparacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoPreparacion");
                OnTiempoPreparacionChanged();
            }
        }
        private global::System.String _TiempoPreparacion;
        partial void OnTiempoPreparacionChanging(global::System.String value);
        partial void OnTiempoPreparacionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDVModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Usuario CreateUsuario(global::System.Int64 id)
        {
            Usuario usuario = new Usuario();
            usuario.id = id;
            return usuario;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pwd
        {
            get
            {
                return _pwd;
            }
            set
            {
                OnpwdChanging(value);
                ReportPropertyChanging("pwd");
                _pwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pwd");
                OnpwdChanged();
            }
        }
        private global::System.String _pwd;
        partial void OnpwdChanging(global::System.String value);
        partial void OnpwdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDVModel", Name="Venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Venta.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static Venta CreateVenta(global::System.Int64 id)
        {
            Venta venta = new Venta();
            venta.id = id;
            return venta;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String folio
        {
            get
            {
                return _folio;
            }
            set
            {
                OnfolioChanging(value);
                ReportPropertyChanging("folio");
                _folio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("folio");
                OnfolioChanged();
            }
        }
        private global::System.String _folio;
        partial void OnfolioChanging(global::System.String value);
        partial void OnfolioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                Onid_productoChanging(value);
                ReportPropertyChanging("id_producto");
                _id_producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_producto");
                Onid_productoChanged();
            }
        }
        private Nullable<global::System.Int64> _id_producto;
        partial void Onid_productoChanging(Nullable<global::System.Int64> value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_receta
        {
            get
            {
                return _id_receta;
            }
            set
            {
                Onid_recetaChanging(value);
                ReportPropertyChanging("id_receta");
                _id_receta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_receta");
                Onid_recetaChanged();
            }
        }
        private Nullable<global::System.Int64> _id_receta;
        partial void Onid_recetaChanging(Nullable<global::System.Int64> value);
        partial void Onid_recetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _cantidad;
        partial void OncantidadChanging(Nullable<global::System.Decimal> value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _total;
        partial void OntotalChanging(Nullable<global::System.Decimal> value);
        partial void OntotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha;
        partial void OnfechaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaChanged();

        #endregion
    
    }

    #endregion
    
}
